# Generated by Django 4.2.2 on 2023-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('blood_group', models.CharField(default='unknow', max_length=50)),
                ('married_status', models.CharField(max_length=120, null=True)),
                ('gender', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='unknow', max_length=150),
        ),
    ]
